/**
 * Generate src/lib/lyrics.ts from docs/songbook/*.txt.
 * Extracts the verbatim LYRICS: block of each track so the Music surface can
 * render full lyrics without runtime fs access. Source of truth stays in docs/.
 *
 * Run: node scripts/gen-lyrics.mjs
 */
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const SONGBOOK = resolve(ROOT, "docs/songbook");
const OUT = resolve(ROOT, "src/lib/lyrics.ts");

// Track number (from the "NN - " filename prefix) → slug, mirroring TRACKS in album.ts.
const SLUG_BY_N = {
  1: "villain",
  2: "down-here",
  3: "who-tf",
  4: "chaos",
  5: "stupid-little-bitch",
  6: "lights-go-low",
  7: "no-saints",
  8: "upbeat-gospel",
  9: "the-old-song",
  10: "the-truth",
  11: "parasitic-love",
  12: "came-back-wrong",
  13: "throne-at-the-bottom",
  14: "apathy-vs-agony",
};

function extractLyrics(raw) {
  // Everything after the first line that is exactly "LYRICS:" (case-insensitive),
  // trimmed of surrounding blank lines. Preserves internal structure verbatim.
  const idx = raw.search(/^LYRICS:\s*$/im);
  if (idx === -1) throw new Error("no LYRICS: marker");
  const after = raw.slice(idx).replace(/^LYRICS:\s*\n/i, "");
  return after.replace(/\s+$/g, "").replace(/^\s*\n/, "");
}

const files = readdirSync(SONGBOOK)
  .filter((f) => f.endsWith(".txt"))
  .sort();

const entries = [];
for (const file of files) {
  const n = Number(file.slice(0, 2));
  const slug = SLUG_BY_N[n];
  if (!slug) throw new Error(`no slug mapped for ${file}`);
  const raw = readFileSync(resolve(SONGBOOK, file), "utf8");
  const lyrics = extractLyrics(raw);
  entries.push([slug, lyrics]);
}

if (entries.length !== 14) throw new Error(`expected 14 tracks, got ${entries.length}`);

const body = entries
  .map(([slug, lyrics]) => {
    // Use a JSON string literal so all escaping (quotes, newlines, unicode) is exact/verbatim.
    return `  ${JSON.stringify(slug)}: ${JSON.stringify(lyrics)},`;
  })
  .join("\n");

const out = `/**
 * AUTO-GENERATED by scripts/gen-lyrics.mjs — do not edit by hand.
 * Full verbatim lyrics for each track, keyed by TRACKS slug.
 * Source of truth: docs/songbook/*.txt (the LYRICS: block).
 */

export const FULL_LYRICS: Record<string, string> = {
${body}
};
`;

writeFileSync(OUT, out);
console.log(`Wrote ${OUT} with ${entries.length} tracks.`);
